const ASR_MODEL="onnx-community/whisper-small";
const LLM_MODEL="Qwen2.5-1.5B-Instruct-q4f16_1-MLC";
const DRAFT_KEY="tongshengyiji-lecture-draft-v2";
const SEGMENT_MS=10000;
const $=id=>document.getElementById(id);
let asr=null,llm=null,stream=null,recorder=null,recording=false,paused=false,summarizing=false,summaryGenerated=false,rotateTimer=null,startedAt=0,elapsedBeforeStart=0,clockTimer=null,work=Promise.resolve(),translationWork=Promise.resolve(),allText=[],allTranslations=[],turnDone=null,setupOk=false;
const langLabel={chinese:"Chinese",english:"English",english_indian:"English",english_sea:"English",japanese:"Japanese",korean:"Korean",malay:"Malay",french:"French",german:"German",spanish:"Spanish"};
function note(s){$("notice").textContent=s;$("stateText").textContent=s}
function progress(t,p){$("progressWrap").classList.remove("hidden");$("progressText").textContent=t;$("progressPct").textContent=p==null?"":`${Math.round(p)}%`;$("progressBar").style.width=`${Math.max(0,Math.min(100,p||0))}%`}
function elapsed(){return elapsedBeforeStart+(recording&&!paused?Date.now()-startedAt:0)}
function timecode(ms){const n=Math.floor(ms/1000);return `${String(Math.floor(n/3600)).padStart(2,"0")}:${String(Math.floor(n%3600/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`}
function persist(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify({allText,allTranslations,elapsed:elapsedBeforeStart,summary:summaryGenerated?$("summaryText").textContent:"",summaryGenerated}))}catch(e){console.warn("Local draft could not be saved",e)}}
function restore(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");if(!d)return;allText=Array.isArray(d.allText)?d.allText:[];allTranslations=Array.isArray(d.allTranslations)?d.allTranslations:[];elapsedBeforeStart=Number(d.elapsed)||0;$("elapsed").textContent=timecode(elapsedBeforeStart);allText.forEach((t,i)=>append(t,allTranslations[i]||""));const savedSummary=String(d.summary||"").trim();summaryGenerated=d.summaryGenerated===true;if(summaryGenerated&&savedSummary)$("summaryText").textContent=savedSummary;$("generateSummary").disabled=!setupOk||!allText.length;if(allText.length)note(`已恢复本机课程记录，共 ${allText.length} 个语音片段。`)}catch(e){console.warn("Saved draft is unavailable",e)}}
async function refreshAudioInputs(){if(!navigator.mediaDevices?.enumerateDevices)return;try{const selected=$("audioInput").value,inputs=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==="audioinput");$("audioInput").replaceChildren(new Option("系统默认麦克风",""));inputs.forEach((d,i)=>$("audioInput").add(new Option(d.label||`麦克风 ${i+1}`,d.deviceId)));if(inputs.some(d=>d.deviceId===selected))$("audioInput").value=selected}catch(e){console.warn("Could not list audio inputs",e)}}
async function loadLibs(){
  const {pipeline,env}=await import("https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1");
  env.useBrowserCache=true;env.allowLocalModels=false;
  asr=await pipeline("automatic-speech-recognition",ASR_MODEL,{device:"webgpu",dtype:"q4",progress_callback:x=>{if(x.status==="progress")progress("下载高准确度多语种语音模型…",x.progress);else if(x.status==="ready")progress("语音模型就绪",100)}});
  progress("准备较强的本机翻译与总结模型…",0);
  const {CreateMLCEngine}=await import("https://esm.run/@mlc-ai/web-llm@0.2.80");
  llm=await CreateMLCEngine(LLM_MODEL,{initProgressCallback:p=>progress(p.text||"下载语言模型…",p.progress*100)});
}
async function prepare(){if(!window.isSecureContext){alert("需要安全的 HTTPS 网页才能在 iPhone/iPad 使用麦克风和本机模型。电脑上的 localhost 地址不能直接作为手机网址；请先发布网页，再用 Safari 打开 HTTPS 地址。");return}if(!navigator.gpu){alert("当前浏览器没有提供 WebGPU。请用最新版 Safari，并更新 iOS/iPadOS。");return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert("当前浏览器不支持网页录音，请更新 iOS/iPadOS 并使用 Safari。");return}$("prepare").disabled=true;note("正在准备本机模型。首次下载约需 2 GB 以上，请连接 Wi‑Fi 并保持 Safari 在前台…");try{await loadLibs();setupOk=true;$("prepare").textContent="模型已准备好";$("modelStatus").textContent="模型已下载并缓存。后续可尝试离线使用；请保持 Safari 在前台处理长课程。";$("start").disabled=false;$("translateText").disabled=false;$("generateSummary").disabled=!allText.length;note("模型就绪；课堂录音和处理都在本机完成。")}catch(e){console.error(e);$("modelStatus").textContent=`准备失败：${e.message||e}`;$("prepare").disabled=false;note("模型没有准备完成。请检查 Wi‑Fi、可用空间和 Safari WebGPU 支持后重试；若 Safari 已清理缓存，需要重新下载模型。")}}
function append(a,b){const box=$("segments");box.querySelector(".empty")?.remove();const row=document.createElement("div");row.className="segment";const left=document.createElement("div"),right=document.createElement("div");left.textContent=a;right.textContent=b||"翻译中…";right.className="translation";row.append(left,right);box.append(row);box.scrollTop=box.scrollHeight;return right}
async function textModel(prompt,maxTokens=450){const r=await llm.chat.completions.create({messages:[{role:"system",content:"You are a careful multilingual classroom interpreter and study-note writer. Preserve names, technical terms, numbers, definitions, and uncertainty. Never invent missing information."},{role:"user",content:prompt}],temperature:0.15,max_tokens:maxTokens});return r.choices?.[0]?.message?.content?.trim()||""}
async function translate(text){const source=$("source").value,accent=source==="english_indian"?"The speaker may use Indian-accented English. Interpret cautiously and preserve the intended meaning only when the wording and context support it.":source==="english_sea"?"The speaker may use Malaysian or Southeast Asian English, including local phrasing or code-switching. Preserve local terms and interpret cautiously.":"";return textModel(`Translate the classroom speech into ${$("target").value}. ${accent} Preserve names, terms, numbers, equations, examples, and local terms. Return only a concise, faithful translation. Correct a recognition slip only if unambiguous; mark uncertain wording [unclear].\n\n${text}`,100)}
async function audioToSamples(blob){const ctx=new AudioContext();try{const raw=await ctx.decodeAudioData(await blob.arrayBuffer());const mono=new Float32Array(raw.length);for(let c=0;c<raw.numberOfChannels;c++){const d=raw.getChannelData(c);for(let i=0;i<d.length;i++)mono[i]+=d[i]/raw.numberOfChannels}if(raw.sampleRate===16000)return mono;const length=Math.ceil(mono.length*16000/raw.sampleRate),out=new Float32Array(length),ratio=raw.sampleRate/16000;for(let i=0;i<length;i++){const x=i*ratio,j=Math.floor(x),f=x-j;out[i]=(mono[j]||0)*(1-f)+(mono[j+1]||0)*f}return out}finally{await ctx.close()}}
function queueTranslation(text){const task=translationWork.then(()=>translate(text));translationWork=task.catch(e=>{note(`翻译片段失败：${e.message||e}`);return ""});return task}
async function handleBlob(blob,recordedAt=elapsed()){if(!blob||blob.size<500)return;try{const samples=await audioToSamples(blob);if(samples.length<8000)return;const source=$("source").value,opts={sampling_rate:16000,task:"transcribe"};if(source!=="auto")opts.language=langLabel[source];const result=await asr(samples,opts);const original=(result.text||"").trim();if(!original)return;const tagged=`[${timecode(recordedAt)}] ${original}`;allText.push(tagged);const index=allText.length-1;allTranslations[index]="";const slot=append(tagged,"翻译中…");queueTranslation(original).then(translated=>{allTranslations[index]=translated;slot.textContent=translated||"（未生成译文，请核对）";persist()}).catch(e=>{allTranslations[index]="";slot.textContent="翻译失败，请核对原文";console.error(e);persist()});persist();note("正在聆听 · 识别与翻译都在本机进行")}catch(e){console.error(e);note(`片段识别失败：${e.message||e}`)}}
function startRecorder(){if(!recording||paused)return;const mime=MediaRecorder.isTypeSupported("audio/mp4")?"audio/mp4":(MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"");recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data?.size){const recordedAt=elapsed();work=work.then(()=>handleBlob(e.data,recordedAt))}};recorder.onstop=()=>{if(recording&&!paused){startRecorder();rotateTimer=setTimeout(rotateRecorder,SEGMENT_MS)}else if(!recording&&turnDone)turnDone()};recorder.start()}
function rotateRecorder(){if(recording&&!paused&&recorder?.state==="recording")recorder.stop()}
function updateClock(){const n=elapsed();$("elapsed").textContent=timecode(n)}
async function start(){if(!setupOk||summarizing)return;try{const classroom=$("pickupMode").value==="classroom",audio={echoCancellation:!classroom,noiseSuppression:!classroom,autoGainControl:true,channelCount:1},deviceId=$("audioInput").value;if(deviceId)audio.deviceId={exact:deviceId};stream=await navigator.mediaDevices.getUserMedia({audio});await refreshAudioInputs();$("summaryText").textContent="";summaryGenerated=false;persist();recording=true;paused=false;startedAt=Date.now();startRecorder();rotateTimer=setTimeout(rotateRecorder,SEGMENT_MS);clockTimer=setInterval(updateClock,500);$("start").disabled=true;$("generateSummary").disabled=true;$("pause").disabled=false;$("pause").textContent="暂停";$("stop").disabled=false;note(`正在录课 · ${classroom?"大教室收音模式":"近距离收音模式"} · 每 10 秒识别一个片段。请保持页面在前台`)}catch(e){note(`麦克风无法启动：${e.message}`)}}
function pause(){if(!recording)return;if(!paused){paused=true;elapsedBeforeStart+=Date.now()-startedAt;clearTimeout(rotateTimer);$("pause").textContent="继续录音";updateClock();note("录音已暂停；点“继续录音”可接着记同一堂课。");if(recorder?.state==="recording")recorder.stop()}else{paused=false;startedAt=Date.now();$("pause").textContent="暂停";startRecorder();rotateTimer=setTimeout(rotateRecorder,SEGMENT_MS);note("继续录课 · 记录会追加到同一堂课")}}
async function summarizeAll(){if(!allText.length){note("没有可总结的语音内容。");return}note("正在分段整理整堂课程…");const text=allText.join("\n"),chunks=[];let rest=text;while(rest.length>2400){let cut=rest.lastIndexOf("\n",2400);if(cut<1200)cut=2400;chunks.push(rest.slice(0,cut));rest=rest.slice(cut)}if(rest)chunks.push(rest);const notes=[];for(let i=0;i<chunks.length;i++){note(`整理课程内容 ${i+1}/${chunks.length}…`);notes.push(await textModel(`请从下面的课堂逐字稿片段中尽可能完整地提取信息，用中文写详细笔记。务必分别检查并记录：\n一、课程知识：主题、目标、概念定义、讲解逻辑、步骤/因果关系、例子、数据、公式。\n二、老师强调：反复提到、明确要求掌握或可能考核的内容。\n三、课程外但课堂中提到的事宜：作业、考试、截止时间、提交方式、材料、教室/课程安排、学校或班级通知、活动及其他杂项。\n四、问题与后续行动：谁需要做什么、何时完成；原文未说的负责人或期限写“未说明”。\n五、听不清/有歧义的专有名词、数字、日期，列为“待核对”，不要猜。\n按转写中的时间戳标注证据；不要把没有说过的信息补进去，不确定讲话人时不要断言是老师。重复信息合并，但不同事项都保留。\n\n课堂逐字稿片段 ${i+1}/${chunks.length}:\n${chunks[i]}`,850))}let finalInput=notes.join("\n\n");while(finalInput.length>8000){const reduced=[];for(let i=0;i<finalInput.length;i+=7000)reduced.push(await textModel(`合并以下课堂分段笔记，供生成整堂课总结。尽量保留全部知识点、通知、作业、考试、日期时间、地点、要求、负责人、例子、数据、疑问和时间戳；去重但不丢事项；不确定处仍标记待核对；不得推测补造。\n\n${finalInput.slice(i,i+7000)}`,850));finalInput=reduced.join("\n\n")}return textModel(`请根据以下全课分段笔记生成一份尽量完整、详细、方便课后复习的中文课堂记录。不要只总结学科内容，老师讲的课程外安排和杂项也要保留。严格按下列标题组织：\n【课程主题与学习目标】\n【课程内容与知识要点】按概念、定义、讲解顺序、步骤/因果关系展开，并保留例子、数据、公式。\n【老师特别强调 / 可能考核】只收录逐字稿有依据的内容。\n【作业、考试与课程要求】逐项列出任务、截止日期、提交方式、材料要求；没提到就写“课堂未提及”。\n【通知与其他事宜】记录课程/学校/班级安排、活动、时间地点、变更及其他课堂杂项。\n【待办清单】每项写事项、负责人、时间；未说明的字段明确写“未说明”。\n【问题与待核对】包括听不清的词、人名、专有名词、数字、日期和不确定转写；附对应时间戳。\n【课后复习清单】\n保留重要时间戳；合并重复项但不得遗漏不同事项。区分老师明确说的、其他发言者说的和无法确认讲话人的内容；不得猜测，不得用常识补全。\n\n${finalInput}`,2000)}
async function stop(){if(!recording)return;const wasPaused=paused;recording=false;paused=false;if(!wasPaused)elapsedBeforeStart+=Date.now()-startedAt;clearTimeout(rotateTimer);clearInterval(clockTimer);$("pause").disabled=true;$("stop").disabled=true;note("正在处理最后一段语音和译文…");await new Promise(resolve=>{turnDone=resolve;if(recorder?.state==="recording")recorder.stop();else{turnDone=null;resolve()}});turnDone=null;stream?.getTracks().forEach(t=>t.stop());await work;await translationWork;persist();$("start").disabled=false;$("generateSummary").disabled=!setupOk||!allText.length;if(!allText.length){note("还没有识别到语音；请确认麦克风权限和音量。");return}note("录音已结束。逐字稿已保存；点击“生成课堂总结”查看详细笔记。")}
async function generateSummary(){if(recording||summarizing||!setupOk||!allText.length)return;summarizing=true;$("generateSummary").disabled=true;$("start").disabled=true;$("summaryText").textContent="";summaryGenerated=false;note("正在生成详细课堂总结…");try{await work;await translationWork;const summary=await summarizeAll();$("summaryText").textContent=summary;summaryGenerated=Boolean(summary);persist();note("详细课堂总结已生成并保存在本机。")}catch(e){note(`总结失败：${e.message||e}`)}finally{summarizing=false;$("generateSummary").disabled=!allText.length;$("start").disabled=!setupOk}}
function exportTranscript(){if(!allText.length){note("还没有逐字稿可导出。");return}const body=allText.map((t,i)=>`${t}\n${allTranslations[i]?`译文：${allTranslations[i]}`:""}`).join("\n\n");const blob=new Blob([`同声译记课堂逐字稿\n\n${body}`],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`课堂逐字稿-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function newLesson(){if(recording||summarizing){note("请先结束当前操作，再新建课程。");return}if(!confirm("新建课程会清空当前页面保存的逐字稿和译文。确定继续吗？"))return;allText=[];allTranslations=[];elapsedBeforeStart=0;summaryGenerated=false;localStorage.removeItem(DRAFT_KEY);$("segments").innerHTML='<p class="empty">语音片段、时间点和译文会显示在这里；长课请保持屏幕和网页打开。</p>';$("summaryText").textContent="";$("generateSummary").disabled=true;$("elapsed").textContent="00:00:00";note("已新建课程。")}
$("prepare").onclick=prepare;$("start").onclick=start;$("pause").onclick=pause;$("stop").onclick=stop;$("generateSummary").onclick=generateSummary;$("exportTranscript").onclick=exportTranscript;$("newLesson").onclick=newLesson;$("translateText").onclick=async()=>{const s=$("manualText").value.trim();if(!s)return;$("translateText").disabled=true;try{const t=await queueTranslation(s),tagged=`[${timecode(elapsed())}] ${s}`,index=allText.length;append(tagged,t);allText.push(tagged);allTranslations[index]=t;summaryGenerated=false;$("summaryText").textContent="";$("generateSummary").disabled=false;persist();$("manualText").value=""}catch(e){note(`翻译失败：${e.message||e}`)}finally{$("translateText").disabled=!setupOk}};
$("installHelp").onclick=()=>$("help").showModal();$("closeHelp").onclick=()=>$("help").close();refreshAudioInputs();navigator.mediaDevices?.addEventListener("devicechange",refreshAudioInputs);restore();if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(e=>console.warn("Service worker unavailable",e));if(!navigator.gpu)$("modelStatus").textContent="当前浏览器未提供 WebGPU；请更新 Safari 和 iOS/iPadOS。";
function explainMobileEnvironment(){const host=location.hostname,localHost=host==="localhost"||host==="127.0.0.1"||host==="::1";if(localHost){$("hostStatus").textContent="当前是电脑本机测试地址，只能在这台电脑打开。iPhone / iPad 要使用发布后的 HTTPS 地址；手机上输入 localhost 会指向手机本身。"}else if(!window.isSecureContext){$("hostStatus").textContent="当前网址不是安全 HTTPS。iPhone / iPad 的麦克风和本机模型需要 HTTPS，请使用 Safari 打开安全网址。"}else{$("hostStatus").textContent="安全网页已就绪。首次准备模型需要联网；开始录音时请允许 Safari 使用麦克风。"}if(!navigator.gpu){$("modelStatus").textContent="此浏览器没有 WebGPU，无法运行本机 AI 模型。请更新 iOS/iPadOS，并使用最新版 Safari。"}else if(!navigator.mediaDevices?.getUserMedia){$("modelStatus").textContent="此浏览器无法访问麦克风。请使用 Safari，并在系统设置中允许麦克风权限。"}}
explainMobileEnvironment();
